#+TITLE: My Emacs Configuration
#+SETUPFILE: html-export.setup
#+STARTUP: overview
#+OPTIONS: H:3 toc:nil
#+EXPORT_FILE_NAME: index

Here begins my [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Init-File.html][init file]], the first one that will be loaded to
initialize [[https://https://www.gnu.org/software/emacs/][Emacs]]. The configurations are split in five modules :

| Module    | Description                                        |
|-----------+----------------------------------------------------|
| [[#config--bootstrap][bootstrap]] | The bootstrapping of Emacs                         |
| [[#config--exwm][exwm]]      | Emacs X Window Manager (when used)                 |
| [[#config--ui][ui]]        | The user interface configurations                  |
| [[#config--app][app]]       | Applications configurations                        |
| [[#config--ides][ides]]      | Integrated development environments configurations |

So let's start our configuration journey...

#+TOC: headlines:3

* The FIle Header

#+BEGIN_SRC emacs-lisp :tangle init.el
;;; init.el --- My Emacs Config -*- lexical-binding: t; -*-
;; Author: Jean Gregory Verret
;; Url: https://github.com/medivhok/my-emacs-config
;; Code:
(setq user-full-name "Jean Gregory Verret"
      user-mail-address "gregory.verret@gmail.com")
#+END_SRC

* The Configurations Environment

I prefer to define some configuration variables in a ~let~ environment to avoid poluting the already saturated Emacs ecosystem. Those variables will be available in my configurations modules during loading, and will disapear after.

#+BEGIN_SRC emacs-lisp :tangle init.el :noweb no-export
  (let* ((medivhok:cfg-directory
          (file-name-as-directory user-emacs-directory))
         <<env:definitions>>
         (init-file-name "init.el"))
          <<env:body>>
  )
  ;; init.el ends here.
#+END_SRC

* From Nothing to Something (Bootstrap)
:PROPERTIES:
:custom_id: config--bootstrap
:END:

The [[./+bootstrap/][bootstrap]] module loading.

#+BEGIN_SRC emacs-lisp :noweb-ref env:definitions
  (medivhok:cfg:bootstrap-directory
   (file-name-as-directory (expand-file-name "+bootstrap" medivhok:cfg-directory)))
#+END_SRC

#+BEGIN_SRC emacs-lisp :noweb-ref env:body
  (load-file (expand-file-name init-file-name medivhok:cfg:bootstrap-directory))
#+END_SRC

* Emacs X Window Manager
:PROPERTIES:
:custom_id: config--exwm
:END:

The [[./+exwm/][exwm]] module loading.

#+BEGIN_SRC emacs-lisp :noweb-ref env:definitions
  (medivhok:cfg:exwm-directory
   (file-name-as-directory (expand-file-name "+exwm" medivhok:cfg-directory)))
#+END_SRC

#+BEGIN_SRC emacs-lisp :noweb-ref env:body
  (load-file (expand-file-name init-file-name medivhok:cfg:exwm-directory))
#+END_SRC

* The User Interface
:PROPERTIES:
:custom_id: config--ui
:END:

The [[./+ui/][ui]] module loading.

#+BEGIN_SRC emacs-lisp :noweb-ref env:definitions
  (medivhok:cfg:ui-directory
   (file-name-as-directory (expand-file-name "+ui" medivhok:cfg-directory)))
#+END_SRC

#+BEGIN_SRC emacs-lisp :noweb-ref env:body
  (load-file (expand-file-name init-file-name medivhok:cfg:ui-directory))
#+END_SRC

* Applications
:PROPERTIES:
:custom_id: config--app
:END:

The [[./+app/][app]] module loading.

#+BEGIN_SRC emacs-lisp :noweb-ref env:definitions
  (medivhok:cfg:app-directory
   (file-name-as-directory (expand-file-name "+app" medivhok:cfg-directory)))
#+END_SRC

#+BEGIN_SRC emacs-lisp :noweb-ref env:body
  (load-file (expand-file-name init-file-name medivhok:cfg:app-directory))
#+END_SRC

* Integrated Development Environments
:PROPERTIES:
:custom_id: config--ides
:END:

The [[./+ides/][ides]] module loading.

#+BEGIN_SRC emacs-lisp :noweb-ref env:definitions
  (medivhok:cfg:ides-directory
   (file-name-as-directory (expand-file-name "+ides" medivhok:cfg-directory)))
#+END_SRC

#+BEGIN_SRC emacs-lisp :noweb-ref env:body
  (load-file (expand-file-name init-file-name medivhok:cfg:ides-directory)))
#+END_SRC
